global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'https://us-central1-prime-ember-454418-t8.cloudfunctions.net/scale_trigger3'
        send_resolved: true
        http_config:
          follow_redirects: true
          bearer_token: "eyJhbGciOiJSUzI1NiIsImtpZCI6ImVlMTkzZDQ2NDdhYjRhMzU4NWFhOWIyYjNiNDg0YTg3YWE2OGJiNDIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIzMjU1NTk0MDU1OS5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImF1ZCI6IjMyNTU1OTQwNTU5LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAyNDgyODQ5OTEzNzM5MzM0NjQzIiwiZW1haWwiOiJiaGF2bmEzMDEyLmd1cHRhdmNjQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhdF9oYXNoIjoiT1ZqQ0toOFRaTnE4M1J1TDNSMnVBdyIsImlhdCI6MTc0Mjc0NDc1NiwiZXhwIjoxNzQyNzQ4MzU2fQ.T0pSwpGoIe4e8GFeXCAep67jwgtcT8VD9Pc7FYLiy_X0UGb3cd8RIgv01u9Io2yDjvzdZE3dpL6hlnDxpzMFEn16Ti-bEZOklSkwiUtvgi1qitG9KdIyZpTYlNuAIoaivKL0APouoZ87VXpofDyH0FY9a1qI-pr-qSGevzwAl0o-Wremkpxxh68SaVIGIWh5aYvjo1-V595xVxhAkbhqcN_eCjqxBrzsGR3L7pVGfiz_EENJSuwobaBrt_lwPlfhRbEWQVYFlZIiayfB8RIu-J8E3GuSSqDrglFC5bB4LlrMCXl4FvXjeAoM1xFO9DejayBGwPXyqdQ3jRvk-Klpdg"
